/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ReclamationsRouteImport } from './routes/reclamations'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KhlayelRouteImport } from './routes/khlayel'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BacRouteImport } from './routes/bac'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CoursesSubjectSlugRouteImport } from './routes/courses.$subjectSlug'
import { Route as AdminModuleRouteImport } from './routes/admin.$module'
import { Route as CoursesSubjectSlugIndexRouteImport } from './routes/courses.$subjectSlug.index'
import { Route as CoursesSubjectSlugChapterSlugRouteImport } from './routes/courses.$subjectSlug.$chapterSlug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamationsRoute = ReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KhlayelRoute = KhlayelRouteImport.update({
  id: '/khlayel',
  path: '/khlayel',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BacRoute = BacRouteImport.update({
  id: '/bac',
  path: '/bac',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSubjectSlugRoute = CoursesSubjectSlugRouteImport.update({
  id: '/$subjectSlug',
  path: '/$subjectSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminModuleRoute = AdminModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSubjectSlugIndexRoute = CoursesSubjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSubjectSlugRoute,
} as any)
const CoursesSubjectSlugChapterSlugRoute =
  CoursesSubjectSlugChapterSlugRouteImport.update({
    id: '/$chapterSlug',
    path: '/$chapterSlug',
    getParentRoute: () => CoursesSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bac': typeof BacRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/khlayel': typeof KhlayelRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/parent': typeof ParentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reclamations': typeof ReclamationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/teacher': typeof TeacherRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/$module': typeof AdminModuleRoute
  '/courses/$subjectSlug': typeof CoursesSubjectSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$subjectSlug/$chapterSlug': typeof CoursesSubjectSlugChapterSlugRoute
  '/courses/$subjectSlug/': typeof CoursesSubjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bac': typeof BacRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/khlayel': typeof KhlayelRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/parent': typeof ParentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reclamations': typeof ReclamationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/teacher': typeof TeacherRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$subjectSlug/$chapterSlug': typeof CoursesSubjectSlugChapterSlugRoute
  '/courses/$subjectSlug': typeof CoursesSubjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bac': typeof BacRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/khlayel': typeof KhlayelRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/parent': typeof ParentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reclamations': typeof ReclamationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/teacher': typeof TeacherRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/$module': typeof AdminModuleRoute
  '/courses/$subjectSlug': typeof CoursesSubjectSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$subjectSlug/$chapterSlug': typeof CoursesSubjectSlugChapterSlugRoute
  '/courses/$subjectSlug/': typeof CoursesSubjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bac'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/khlayel'
    | '/login'
    | '/market'
    | '/parent'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/reclamations'
    | '/subscriptions'
    | '/teacher'
    | '/team'
    | '/terms'
    | '/admin/$module'
    | '/courses/$subjectSlug'
    | '/admin/'
    | '/courses/'
    | '/courses/$subjectSlug/$chapterSlug'
    | '/courses/$subjectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bac'
    | '/dashboard'
    | '/events'
    | '/khlayel'
    | '/login'
    | '/market'
    | '/parent'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/reclamations'
    | '/subscriptions'
    | '/teacher'
    | '/team'
    | '/terms'
    | '/admin/$module'
    | '/admin'
    | '/courses'
    | '/courses/$subjectSlug/$chapterSlug'
    | '/courses/$subjectSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bac'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/khlayel'
    | '/login'
    | '/market'
    | '/parent'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/reclamations'
    | '/subscriptions'
    | '/teacher'
    | '/team'
    | '/terms'
    | '/admin/$module'
    | '/courses/$subjectSlug'
    | '/admin/'
    | '/courses/'
    | '/courses/$subjectSlug/$chapterSlug'
    | '/courses/$subjectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BacRoute: typeof BacRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  KhlayelRoute: typeof KhlayelRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  ParentRoute: typeof ParentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ReclamationsRoute: typeof ReclamationsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TeacherRoute: typeof TeacherRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamations': {
      id: '/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof ReclamationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khlayel': {
      id: '/khlayel'
      path: '/khlayel'
      fullPath: '/khlayel'
      preLoaderRoute: typeof KhlayelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac': {
      id: '/bac'
      path: '/bac'
      fullPath: '/bac'
      preLoaderRoute: typeof BacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$subjectSlug': {
      id: '/courses/$subjectSlug'
      path: '/$subjectSlug'
      fullPath: '/courses/$subjectSlug'
      preLoaderRoute: typeof CoursesSubjectSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/$module': {
      id: '/admin/$module'
      path: '/$module'
      fullPath: '/admin/$module'
      preLoaderRoute: typeof AdminModuleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$subjectSlug/': {
      id: '/courses/$subjectSlug/'
      path: '/'
      fullPath: '/courses/$subjectSlug/'
      preLoaderRoute: typeof CoursesSubjectSlugIndexRouteImport
      parentRoute: typeof CoursesSubjectSlugRoute
    }
    '/courses/$subjectSlug/$chapterSlug': {
      id: '/courses/$subjectSlug/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/courses/$subjectSlug/$chapterSlug'
      preLoaderRoute: typeof CoursesSubjectSlugChapterSlugRouteImport
      parentRoute: typeof CoursesSubjectSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModuleRoute: typeof AdminModuleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModuleRoute: AdminModuleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesSubjectSlugRouteChildren {
  CoursesSubjectSlugChapterSlugRoute: typeof CoursesSubjectSlugChapterSlugRoute
  CoursesSubjectSlugIndexRoute: typeof CoursesSubjectSlugIndexRoute
}

const CoursesSubjectSlugRouteChildren: CoursesSubjectSlugRouteChildren = {
  CoursesSubjectSlugChapterSlugRoute: CoursesSubjectSlugChapterSlugRoute,
  CoursesSubjectSlugIndexRoute: CoursesSubjectSlugIndexRoute,
}

const CoursesSubjectSlugRouteWithChildren =
  CoursesSubjectSlugRoute._addFileChildren(CoursesSubjectSlugRouteChildren)

interface CoursesRouteChildren {
  CoursesSubjectSlugRoute: typeof CoursesSubjectSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSubjectSlugRoute: CoursesSubjectSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BacRoute: BacRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  KhlayelRoute: KhlayelRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  ParentRoute: ParentRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ReclamationsRoute: ReclamationsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TeacherRoute: TeacherRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
